title: sbstjn.com
email: hi@sbstjn.com
description: Software Engineer and Team Lead living in Hamburg, Germany. Daytime Flight Captain at Jimdo and passionate about Software, Design, People and vegan Food.
baseurl: ""
url: "https://sbstjn.com"
repository: sbstjn/sbstjn.github.io

author:
  twitter: sbstjn

twitter:
  username: sbstjn

facebook:
  publisher: 669118929
  admins: 669118929

permalink: 'pretty'

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md

gems:
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

gist:
  noscript: true

sass:
  sass_dir: 'assets/styles/_sass'
  style: 'compressed'

permalink: /:title.html
